name: test
description: wow
version: 1.0.1
homepage: what

environment:
  sdk: '>=2.13.0 <3.0.0'


dependencies:
  crclib:
    git:
      url: https://github.com/google/crclib.dart.git
      ref: nullsafety
  ffi: ^1.1.2

dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner:
